name: flutter_splash_countdown
description: Automatically generates native code for adding splash screens in Android and iOS. Customize with specific platform, background color and splash image.
version: 0.0.0+2
homepage: https://github.com/upcwangying/flutter_splash_countdown
author: Ying Wang <upcwangying@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  yaml: ^2.1.16
  image: ^2.1.4
  color: ^2.1.1

dev_dependencies:
  pedantic: ^1.8.0+1